from django.conf.urls import url
from .import views as core_views
from django.contrib.auth import views as auth_views

app_name = 'core'

urlpatterns = [
#     url(r'^pinterest-7a703.html/$', core_views.pininterest, name='pin' ),
     url(r'^signup/$', core_views.signup, name='signup'),
     url(r'^signup/resend_link/$', core_views.resend_account_activation, name='resend_link'),
     url(r'^authenticate_display/$', core_views.authenticate_display, name='authenticate_display'),
     url(r'^authenticate/([-\w]+)/login/$', core_views.authenticate_user, name='authenticate_user'),
     url(r'account_activation_sent/$', core_views.account_activation_sent, name='account_activation_sent'),
     url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', core_views.activate, name='activate'),
     url(r'^$', core_views.Home, name='home'),
     url(r'^logout/$',auth_views.LogoutView.as_view(), name='logout'),
#     url(r'^profile/$', core_views.profile, name='profile'),
     url(r'^password_reset/$', auth_views.password_reset, {'post_reset_redirect':'/password_reset/done'}, name='password_reset'),
     url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
     url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
         auth_views.password_reset_confirm,{'post_reset_redirect' : '/reset/done/'}, name='password_reset_confirm'),
     url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
     url(r'^password/$', core_views.change_password, name='change_password'),
     url(r'^profile/name/$', core_views.edit_name, name='editname'),
     url(r'^profile/location/$', core_views.edit_location, name='editlocation'),
     url(r'^profile/bio/$', core_views.edit_bio, name='editbio'),
     url(r'^profile/addlinks/$', core_views.Create_Links, name='addlinks'),
     url(r'^profile/deletelink/([0-9]+)/$', core_views.delete_link, name='deletelink'),
     url(r'^profile/editlink/([0-9]+)/$', core_views.edit_link, name='editlink'),
     url(r'^profile/image/$', core_views.update_crop_propic, name='editpic'),
     url(r'^profile/removepic/$', core_views.remove_propic, name='rempic'),
#    url(r'^create_content/([0-9]+)/$', core_views.create_content, name='create_content'),
     url(r'^createcover/([0-9]+)/$', core_views.create_title_cover, name='createcover'),
     url(r'^create_blog/$', core_views.create_blogs, name='createblogs'),
     url(r'^addcustomtopic/$', core_views.create_customtopic, name='customtopic'),
     url(r'^customtopics/$', core_views.my_customtopics, name='customtopics'),
     url(r'^customtopic/([0-9]+)/$', core_views.customtopic, name='custom_topic'),
     url(r'^more/([-\w]+)/$', core_views.profile_more, name='more'),
     url(r'^more/topics/([0-9]+)/$', core_views.customtopic_blogs, name='custom_blogs'),
     url(r'^add_title/([0-9]+)/([0-9]+)/$', core_views.add_titles_to_customtopic, name='titles_to_customtopic'),
     url(r'^remove_title/([0-9]+)/([0-9]+)/$', core_views.remove_titles_from_customtopic, name='titles_from_customtopic'),
     url(r'^blogpost/([0-9]+)/$', core_views.blog_post, name='blogpost'),
     url(r'^add_blog_pictures/$', core_views.add_blog_pictures, name='add_blog_pictures'),
     url(r'^create_title/$', core_views.create_title, name='create_title'),
#    url(r'^create_subtitle/([0-9]+)/$', core_views.add_subtitles, name='create_subtitle'),
#    url(r'^create_body/([0-9]+)/$', core_views.add_body, name='create_body'),
#    url(r'^create_pictures/([0-9]+)/$', core_views.add_pictures, name='create_pictures'),
#    url(r'^edit_title/([0-9]+)/$', core_views.edit_blog_title, name='edit_title'),
#    url(r'^edit_subtitle/([0-9]+)/([0-9]+)/$', core_views.edit_blog_subtitle, name='edit_subtitle'),
#    url(r'^edit_body/([0-9]+)/([0-9]+)/$', core_views.edit_blog_body, name='edit_body'),
#    url(r'^edit_pictures/([0-9]+)/([0-9]+)/$', core_views.edit_blog_pictures, name='edit_pictures'),
     url(r'^publish/([0-9]+)/$', core_views.publish, name='publish'),
#    url(r'^edit_blog/([0-9]+)/$', core_views.edit_blog, name='edit_blog'),
     url(r'^display/([-\w]+)/comment/$', core_views.add_comment, name='comments'),
     url(r'^comment/([0-9]+)/$', core_views.reply_comment, name='reply'),
     url(r'^delete_comment/([0-9]+)/$', core_views.delete_comment, name='delete_comment'),
     url(r'^users/$', core_views.users, name='users'),
     url(r'^description_theme/([0-9]+)/$', core_views.add_description_theme, name='description_theme'),
     url(r'^writer/([0-9]+)/$', core_views.writer, name='writer'),
     url(r'^myblogs/$', core_views.my_blogs, name='myblogs'),
     url(r'^deleteconfirmblog/([0-9]+)/$', core_views.delete_confirm_blog, name='deleteconfirmblog'),
     url(r'^deleteblog/([0-9]+)/$', core_views.delete_blog, name='deleteblog'),
     url(r'^myblogdisplay/([0-9]+)/$', core_views.my_blog_display, name='myblogdisplay'),
#    url(r'^delete_confirm_body/([0-9]+)/([-\w]+)/$', core_views.delete_confirm_body, name='delete_confirm_body'),
#    url(r'^delete_confirm_pictures/([0-9]+)/([-\w]+)/$', core_views.delete_confirm_pictures, name='delete_confirm_pictures'),
#    url(r'^delete_confirm_subtitles/([0-9]+)/([-\w]+)/$', core_views.delete_confirm_subtitles, name='delete_confirm_subtitles'),
#    url(r'^delete_pictures/([0-9]+)/([-\w]+)/$', core_views.delete_pictures, name='delete_pictures'),
#    url(r'^delete_body/([0-9]+)/([-\w]+)/$', core_views.delete_body, name='delete_body'),
#    url(r'^delete_subtitles/([0-9]+)/([-\w]+)/$', core_views.delete_subtitles, name='delete_subtitles'),
     url(r'^allblogs/$', core_views.allblogs, name='allblogs'),
     url(r'^search-results/$', core_views.search_blogs, name='search_blogs'),
#    url(r'^add_picset_title/([0-9]+)$', core_views.add_picset_title, name='picsettitle'),
#    url(r'^picset_content/([0-9]+)/([0-9]+)/$', core_views.add_picset_content, name='picset_content'),
#    url(r'^add_picset/([0-9]+)/([0-9]+)/$', core_views.add_picset, name='picset'),
     url(r'^contact/$', core_views.contact_view, name='contact'),
     url(r'^privacy_policy/$', core_views.privacy_policy, name='privacy_policy'),
     url(r'^about_us/$', core_views.about_us, name='about_us'),
     url(r'^terms_conditions/$', core_views.terms_conditions, name='terms_conditions'),
     url(r'^create_topic/([-\w]+)/$', core_views.create_topic, name='topic'),
     url(r'^create_subtopic/([-\w]+)/$', core_views.create_subtopic, name='subtopic'),
     url(r'^all_writers/$', core_views.all_writers, name='writers'),
     url(r'^manual_titlesprop/$', core_views.create_manual_titlesprop, name='manual_titlesprop'),
#    url(r'^can_comment/$', core_views.can_comment, name='can_comment'),
     url(r'^areas/([-\w]+)/$', core_views.topic_home, name='topic_home'),
     url(r'^approval_display/([0-9]+)/$', core_views.approval_display, name='approval_display'),
     url(r'^approval_blogs/$', core_views.approval_blogs, name='approval_blogs'),
     url(r'^approve/([0-9]+)/$', core_views.approve, name='approve'),
     url(r'^update_usercover/$', core_views.update_usercover, name='usercover'),
     url(r'^update_theme/$', core_views.add_usercover_theme, name='user_theme'),
     url(r'^add_quote/$', core_views.add_quote, name='add_quote'),
     url(r'^topics/$', core_views.alltopics, name='alltopics'),
     url(r'^topics/([-\w]+)/$', core_views.topic_titles, name='topic_titles'),
     url(r'^add_to_subtopic/([0-9]+)/$', core_views.add_to_subtopic, name='add_to_subtopic'),
     url(r'^topic_more/([-\w]+)/$', core_views.topic_more, name='topic_more'),
     url(r'^subtopics/([-\w]+)/$', core_views.subtopic_blogs, name='subtopic_blogs'),
     url(r'^subtopics/customtopic/([0-9]+)/$', core_views.subtopic_customtopic_blogs, name='subtopic_customtopic_blogs'),
     url(r'^([-\w]+)/$', core_views.profile, name='profile'),
     url(r'^([-\w]+)/blogs/$', core_views.m_profile, name='blogs'),
     url(r'([-\w]+)/blogs/([0-9]+)/([-\w]+)/$', core_views.month_archieve, name='month_archieve'),
     url(r'^([-\w]+)/([-\w]+)/$', core_views.blog_display, name='display'),




]